### ISSUE TITLE
Changing the lower buttons per slide

### ISSUE THREAD

**Issue by JordyVeldhuis** [Appboy/appboy-custom-html5-in-app-message-templates#11]
Hi,

Could somebody tell me how I can change the lower buttons within each slide? I want different buttons on some of them.

Thanks

**Comment by n0prablam** [comment]
@JordyVeldhuis I'm trying to solve this puzzle myself. Let me know if you did this. Thanks!

**Comment by JordyKeolis** [comment]
@n0prablam I'm sorry I am not working with Appboy/Braze anymore!

**Comment by davidbielik** [comment]
closing via #21
