### ISSUE TITLE
Video Embed

### ISSUE THREAD

**Issue by jlapitan** [Appboy/appboy-custom-html5-in-app-message-templates#5]
I tried embedding HTML5 videos, but its not working.

html5 video is working locally but when added on Appboy, and when tried playing the video, the audio is playing but not video at all.

**Comment by radixdev** [comment]
Hey @jlapitan,

Which platforms are you experiencing this issue?

**Comment by jlapitan** [comment]
@radixdev both ios and android, same issue.. audio of the video is playing, but no video at all.

**Comment by davidbielik** [comment]
closing via #21
